package eu.chorevolution.vsb.test.weather.bc;

import java.util.ArrayList;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebService;
import eu.chorevolution.vsb.gm.protocols.builders.ResponseBuilder;
import eu.chorevolution.vsb.gm.protocols.primitives.BcGmComponent;
import eu.chorevolution.vsb.gmdl.utils.Data;

/**
 * This class was generated by the CHOReVOLUTION BindingComponent Generator
 * using com.sun.codemodel 2.6
 * 
 */
@WebService(serviceName = "BindingComponent", targetNamespace = "eu.chorevolution.vsb.test.weather.bc")
public class BindingComponent {

	private final BcGmComponent apiRef;

	public BindingComponent(BcGmComponent apiRef) {
		this.apiRef = apiRef;
	}

	@WebMethod
	public ComplexType weatherInfoByAreaRequest(Integer period, Double latitude, Double longitude, Double radius) {
		List<Data<?>> datas = new ArrayList<Data<?>>();
		datas.add(new Data<Integer>("period", "Integer", true, period, "PATH"));
		datas.add(new Data<Double>("latitude", "Double", true, latitude, "PATH"));
		datas.add(new Data<Double>("longitude", "Double", true, longitude, "PATH"));
		datas.add(new Data<Double>("radius", "Double", true, radius, "PATH"));
		String serializedcomplexType = this.apiRef.mgetTwowaySync(
				"/mes/get_metadata_in_area?collection=weather&period={period}&lat={latitude}&lon={longitude}&radius={radius}", datas);
		System.out.println("Answer from REST: " + serializedcomplexType);

		return ResponseBuilder.unmarshalObject("application/json", serializedcomplexType, ComplexType.class);
	}

}
