package eu.chorevolution.vsb.bcs.weather.bc;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * This class was generated by the CHOReVOLUTION BindingComponent Generator using com.sun.codemodel 2.6
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "RootClass")
public class RootClass {

    @XmlElement(name = "status", required = true)
    private String status;
    @XmlElement(name = "docs", required = true)
    private List<WeatherType> docs;

    public String getstatus() {
        return status;
    }

    public void setstatus(String status) {
        this.status = status;
    }

    public List<WeatherType> getdocs() {
        return docs;
    }

    public void setdocs(List<WeatherType> docs) {
        this.docs = docs;
    }

}
