
package eu.chorevolution.vsb.playgrounds.clientserver.soap.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://test.soap.clientserver.playgrounds.vsb.chorevolution.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://test.soap.clientserver.playgrounds.vsb.chorevolution.eu/", className = "eu.chorevolution.vsb.playgrounds.clientserver.soap.test.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://test.soap.clientserver.playgrounds.vsb.chorevolution.eu/", className = "eu.chorevolution.vsb.playgrounds.clientserver.soap.test.HelloWorldResponse")
    @Action(input = "http://test.soap.clientserver.playgrounds.vsb.chorevolution.eu/HelloWorldService/helloWorldRequest", output = "http://test.soap.clientserver.playgrounds.vsb.chorevolution.eu/HelloWorldService/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
