
package eu.chorevolution.vsb.gm.protocols.dpws;

import org.ws4d.java.service.DefaultService;
import org.ws4d.java.types.URI;


/**
 * This class was generated by the CHOReVOLUTION BindingComponent Generator using com.sun.codemodel 2.6
 * 
 */
public class DPWSService
    extends DefaultService
{

    private final static URI DOCU_EXAMPLE_SERVICE_ID = (new URI(DPWSDevice.DOCU_NAMESPACE + "/DocuExampleService"));

    public DPWSService(BcDPWSSubcomponent subcomponentRef) {
        super();
        setServiceId(DOCU_EXAMPLE_SERVICE_ID);
        operation_1 operation_1;
        operation_1 = new operation_1(subcomponentRef);
        addOperation(operation_1);
    }

}
