
package eu.chorevolution.vsb.gm.protocols.dpws;

import java.util.ArrayList;
import java.util.List;
import eu.chorevolution.vsb.gmdl.utils.Data;
import org.ws4d.java.communication.CommunicationException;
import org.ws4d.java.schema.ComplexType;
import org.ws4d.java.schema.Element;
import org.ws4d.java.schema.SchemaUtil;
import org.ws4d.java.security.CredentialInfo;
import org.ws4d.java.service.InvocationException;
import org.ws4d.java.service.Operation;
import org.ws4d.java.service.parameter.ParameterValue;
import org.ws4d.java.service.parameter.ParameterValueManagement;
import org.ws4d.java.types.QName;


/**
 * This class was generated by the CHOReVOLUTION BindingComponent Generator using com.sun.codemodel 2.6
 * 
 */
public class operation_1
    extends Operation
{

    private BcDPWSSubcomponent subcomponentRef;

    public operation_1(BcDPWSSubcomponent subcomponentRefparam) {
        super("operation_1", new QName("BasicServices", DPWSDevice.DOCU_NAMESPACE));
        subcomponentRef = subcomponentRefparam;
        ComplexType complexInput;
        complexInput = new ComplexType(new QName("complexInput", DPWSDevice.DOCU_NAMESPACE), ComplexType.CONTAINER_SEQUENCE);
        Element arg0Elem;
        arg0Elem = new Element(new QName("arg0", DPWSDevice.DOCU_NAMESPACE), SchemaUtil.TYPE_STRING);
        complexInput.addElement(arg0Elem);
        Element arg1Elem;
        arg1Elem = new Element(new QName("arg1", DPWSDevice.DOCU_NAMESPACE), SchemaUtil.TYPE_STRING);
        complexInput.addElement(arg1Elem);
        Element complexInputElem;
        complexInputElem = new Element(new QName("complexInputElem", DPWSDevice.DOCU_NAMESPACE), complexInput);
        setInput(complexInputElem);
        Element serializedroute;
        serializedroute = new Element(new QName("route", DPWSDevice.DOCU_NAMESPACE), SchemaUtil.TYPE_STRING);
        setOutput(serializedroute);
    }

    public ParameterValue invokeImpl(ParameterValue parameterValue, CredentialInfo credentialInfo)
        throws CommunicationException, InvocationException
    {
        List<Data<?>> datas = new ArrayList<Data<?>>();
        java.lang.String arg0;
        arg0 = ParameterValueManagement.getString(parameterValue, "arg0");
        datas.add(new Data<String>("arg0", "String", true, arg0, "PATH"));
        java.lang.String arg1;
        arg1 = ParameterValueManagement.getString(parameterValue, "arg1");
        datas.add(new Data<String>("arg1", "String", true, arg1, "PATH"));
        java.lang.String serializedroute = this.subcomponentRef.mgetTwowaySync("/maps/api/directions/json?origin={arg0}&destination={arg1}&key=AIzaSyBhfNR1PHo8EsuxjLr3EO-sNnfoUDh4ilw", datas);
        ParameterValue result = createOutputValue();
        ParameterValueManagement.setString(result, "reply", serializedroute);
        return result;
    }

}
