package eu.chorevolution.vsb.gmdl.utils;

public class BcConfiguration {
  private String componentAddress;
  private String componentRole;
  private String bindedSystemAddress;
  private String generatedCodePath = "src/main/resources";
  
  public BcConfiguration() {
    // TODO Auto-generated constructor stub
  }
  
  public BcConfiguration(String jsonConfiguration) {
    // TODO Auto-generated constructor stub
  }
  
  public String getComponentAddress() {
    return componentAddress;
  }

  public void setComponentAddress(String componentAddress) {
    this.componentAddress = componentAddress;
  }
  
  public String getComponentRole() {
    return componentRole;
  }

  public void setComponentRole(String componentRole) {
    this.componentRole = componentRole;
  }
  
  public void setServiceAddress(String serviceAddress) {
    this.bindedSystemAddress = serviceAddress;
  }
  
  public String getServiceAddress() {
    return bindedSystemAddress;
  }
  
  public void setGeneratedCodePath(String generatedCodePath) {
    this.generatedCodePath = generatedCodePath;
  }
  
  public String getGeneratedCodePath() {
    return generatedCodePath;
  }
  
  /* For SOAP */
  private String serviceName = "BindingComponent"; // name of the published interface used by the client, generated by default like {ClassName}Service
  private String targetNamespace = "eu.chorevolution.vsb.bindingcomponent.generated"; // package nameSpace of the service
  
  public void setTargetNamespace(String targetNamespace) {
    this.targetNamespace = targetNamespace;
  }
  
  public String getServiceName() {
    return serviceName;
  }
  
  
  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }
  
  public String getTargetNamespace() {
    return targetNamespace;
  }
}