package eu.chorevolution.vsb.gmdl.utils;

import eu.chorevolution.vsb.gmdl.utils.enums.RoleType;

public class BcConfiguration {
  private String subcomponentAddress;
  private int subcomponentPort;
  private RoleType subcomponentRole;
  private String serviceAddress;
  private int servicePort;
  private String generatedCodePath = "src/main/resources";
  
  public BcConfiguration() {
    // TODO Auto-generated constructor stub
  }
  
  public BcConfiguration(String jsonConfiguration) {
    // TODO Auto-generated constructor stub
  }
  
  public String getSubcomponentAddress() {
    return subcomponentAddress;
  }
  
  public void setSubcomponentAddress(String subcomponentAddress) {
    this.subcomponentAddress = subcomponentAddress;
  }
  
  public int getSubcomponentPort() {
    return subcomponentPort;
  }
  
  public void setSubcomponentPort(int subcomponentPort) {
    this.subcomponentPort = subcomponentPort;
  }
  
  public RoleType getSubcomponentRole() {
    return subcomponentRole;
  }

  public void setSubcomponentRole(RoleType componentRole) {
    this.subcomponentRole = componentRole;
  }
  
  public void setServiceAddress(String serviceAddress) {
    this.serviceAddress = serviceAddress;
  }
  
  public String getServiceAddress() {
    return serviceAddress;
  }
  
  public void setServicePort(int servicePort) {
    this.servicePort = servicePort;
  }
  
  public int getServicePort() {
    return servicePort;
  }
  
  public void setGeneratedCodePath(String generatedCodePath) {
    this.generatedCodePath = generatedCodePath;
  }
  
  public String getGeneratedCodePath() {
    return generatedCodePath;
  }
  

  
  /* For SOAP */
  private String serviceName = "BindingComponent"; // name of the published interface used by the client, generated by default like {ClassName}Service
  private String targetNamespace = "eu.chorevolution.vsb.bindingcomponent.generated"; // package nameSpace of the service
  
  public void setTargetNamespace(String targetNamespace) {
    this.targetNamespace = targetNamespace;
  }
  
  public String getServiceName() {
    return serviceName;
  }
  
  
  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }
  
  public String getTargetNamespace() {
    return targetNamespace;
  }

  public void parseFromJSON(String path) {
    
  }
 
}